version: "3.8"

services:
  db:
    image: postgres:14.0-alpine3.14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secure
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d